Companion/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')), 
    path('api/', include('base.api.urls')), 

    re_path(r'^favicon\.ico$', RedirectView.as_view( url=settings.STATIC_URL + 'images/favicon.ico', permanent=True)),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
]

base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerPage, name="register"),

    path('', views.home, name = "home"),
    path('room_page/<str:pk>/', views.room, name="room"),
    path('profile/<str:pk>/', views.userProfile, name="user-profile"),
    path('update-user/<str:pk>/', views.updateUser, name="update-user"),

    path('createroom/', views.createRoom, name="create-room"),
    path('updateroom/<str:pk>/', views.updateroom, name="update-room"),
    path('deleteroom/<str:pk>/', views.deleteRoom, name="delete-room"),
    path('deletemessage/<str:pk>/', views.deleteMessage , name="delete-message"),


    path('topics/', views.topicsPage , name="topics"),
    path('activity/', views.activityPage , name="activity"),


]

base/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    name = models.CharField(max_length=200, null=False, blank=False)
    email = models.EmailField(unique=True, null=False, blank=False)
    bio = models.TextField(null=True, blank=True)

    avatar = models.ImageField(null=True, blank=True, default="avatar.svg")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    @property
    def avatar_url(self):
        try:
            url = self.avatar.url
        except:
            url = '/media/avatar.svg' 
        return url

class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="rooms", null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length = 200)   
    description = models.TextField(null = True, blank = True)
    participants = models.ManyToManyField(User, related_name="participants", blank=True)    
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ['-updated', '-created']
    
    def __str__(self):      
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_messages")
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="room_messages")
    body = models.TextField()
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now = True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):      
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Room, User


class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name' , 'username' , 'email' , 'password1' , 'password2']
    


class Roomform(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host', 'participants']




class Userform(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']
        exclude = ['host', 'participants']

            

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import roomSerializer

@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET api/',
        'GET api/rooms',
        'GET api/rooms/:id',
    ]

    return Response(routes)



@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = roomSerializer(rooms, many=True)
    return Response(serializer.data)



@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id = pk)
    serializer = roomSerializer(room, many=False)
    return Response(serializer.data)

base/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.contrib.auth import authenticate, login, logout
from django.db.models import Q
from .models import Room, Topic, Message, User
from .forms import Roomform, Userform, MyUserCreationForm


def loginPage(request):
    page = "login"

    if request.user.is_authenticated:
        return  redirect('home')

    if request.method == 'POST':
        email = request.POST.get('email' ).lower()
        password = request.POST.get('password')
        try:
            user = User.objects.get(email = email)
        except:
            messages.error(request, "User does not exist.")
            return redirect('login')
        
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Username or password does not match.")

    context = {'page' : page}
    return render(request, 'base/login.html', context)

def logoutUser(request):
    logout(request)
    return redirect('home')

def registerPage(request):
    form = MyUserCreationForm
    if request.method == 'POST':
        form = MyUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()
            login(request, user)
            return redirect('home')
        else:   
            messages.error(request, 'Please follow the rules while entering details.')
    context = {'form':  form}
    return render(request, 'base/signup.html', context)



def userProfile(request, pk):
    user = User.objects.get(id=pk)
    rooms = user.rooms.all()
    topics = Topic.objects.all()
    user_messages = user.user_messages.all()
    context = {'user': user, 'rooms':rooms, 'topics': topics, 'user_messages': user_messages}
    return render(request, 'base/profile.html', context)



@login_required(login_url='login')
def updateUser(request, pk):
    user = User.objects.get(id=pk)
    if request.user != user:
        return redirect('user-profile', request.user.id)
    
    form = Userform(instance=user)

    if request.method == "POST":
        form = Userform(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('user-profile', user.id)

    context = {'form': form}
    return render(request, 'base/update-user.html', context)



def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    rooms = Room.objects.filter(
        Q(topic__name__icontains = q) |
        Q(name__icontains = q) |
        Q(description__icontains = q) |
        Q(host__username__icontains = q)
    )
    
    topics = Topic.objects.all()[0:5]
    room_cnt = rooms.count()
    room_messages = Message.objects.filter(
        Q(room__topic__name__icontains = q)
    )[:5]

    context = {'rooms': rooms, 'topics': topics, 'room_cnt': room_cnt,
               'room_messages': room_messages} 
    return render(request, 'base/home.html', context)


@never_cache
def room(request, pk):
    room = Room.objects.get(id = pk)

    if request.method == 'POST':
        new_message = Message.objects.create(
                user = request.user,
                room = room,
                body = request.POST.get('body')
        )
        room.participants.add(request.user)
        return redirect('room', pk = room.id)

    messages = room.room_messages.all()
    participants = room.participants.all()
    context = {'room' : room, 'room_messages': messages, 'participants': participants}
    return render(request, 'base/room.html', context)



@login_required(login_url='login')
def createRoom(request):
    form = Roomform()
    topics = Topic.objects.all()
    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)

        Room.objects.create(
            host = request.user,
            topic = topic,
            name = request.POST.get('name'),
            description = request.POST.get('description'),
        )
        return redirect('home')
    
    action = "Create Room"
    context = {'form' : form, 'topics': topics, 'action': action}
    return render(request, 'base/room_form.html', context)



@login_required(login_url='login')  
def updateroom(request, pk):
    room = Room.objects.get(id = pk)
    form = Roomform(instance=room)
    topics = Topic.objects.all()

    if request.user != room.host:
        return HttpResponse("You are not allowed here.")

    if request.method == 'POST':
        topic_name = request.POST.get('topic')
        topic, created = Topic.objects.get_or_create(name=topic_name)

        room.name = request.POST.get('name')
        room.topic = topic
        room.description = request.POST.get('description')
        room.save()
        return redirect('home')
        
    action = "Update Room"
    context = {'form' : form, 'topics': topics, 'action': action, 'room': room}
    return render(request, 'base/room_form.html', context)



@login_required(login_url='login')
def deleteRoom(request, pk):
    room = Room.objects.get(id = pk)
    if request.user != room.host:  
        return render(request, 'base/notallowed.html')  
    if request.method == 'POST':
        room.delete()
        return redirect('home')
    
    return render(request, 'base/delete.html', {'obj' : room})



@login_required(login_url='login')
def deleteMessage(request, pk):
    message = Message.objects.get(id = pk)
    if request.user != message.user:
        return HttpResponse("You are not allowed to delete this message!")
    if request.method == 'POST':
        message.delete()
        return redirect('home')
    
    return render(request, 'base/delete.html', {'obj' : message})




def topicsPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    topics = Topic.objects.filter(
        Q(name__icontains = q)
    )

    context = {'topics': topics}
    return render(request, 'base/topics.html/', context)




def activityPage(request):
    rmessages = Message.objects.all()

    context = {'rmessages': rmessages}
    return render(request, 'base/activity.html/',context)

base/templates/base/activity.html
{% extends 'main.html' %}

{% block content %}


<main class="layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Recent Activities</h3>
        </div>
      </div>

      <div class="activities-page layout__body">
        {% for message in rmessages %}
        <div class="activities__box">
          <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id%}" class="roomListRoom__author">
              <div class="avatar avatar--small">
                <img src="{{message.user.avatar_url}}" />
              </div>
              <p>
                @{{message.user.username}}
                <span>{{message.created|timesince}} ago</span>
              </p>
            </a>
            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
              <a href="{% url 'delete-message' message.id %}">
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                  <title>remove</title>
                  <path
                    d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                  </path>
                </svg>
              </a>
            </div>
            {% endif %}
          </div>
          <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room.name}}</a>”</p>
            <div class="activities__boxRoomContent">
              {{message}}
            </div>
          </div>
        </div>
        {%endfor%}
      </div>
    </div>
  </div>
</main>

<script src="script.js"></script>

{% endblock content %}

base/templates/base/activity_component.html
<div class="activities">
    <div class="activities__header">
        <h2>Recent Activities</h2>
    </div>
    {% for message in messages %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id%}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{message.user.avatar_url}}" />
                </div>
                <p>
                    @{{message.user.username}}
                    <span> {{message.created|timesince}} ago</span>
                </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
                <a href="{% url 'delete-message' message.id %}">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {%endif%}
        </div>
        <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room.name}}</a>”</p>
            <div class="activities__boxRoomContent">
                {{message}}
            </div>
        </div>
    </div>
    {%endfor%}
    <a class="btn btn--link activities__more" href="{% url 'activity' %}">
        More
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <title>arrow-right-slim</title>
            <path d="M11.293 4.707L17.586 11H4v2h13.586l-6.293 6.293 1.414 1.414L21.414 12l-8.707-8.707-1.414 1.414z">
            </path>
        </svg>
    </a>
</div>

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}

<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                        <a href="javascript:history.back()">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                    d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" action="" method="POST">
                    {%csrf_token%}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{obj}}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
<script src="script.js"></script>

{% endblock content %}

base/templates/base/feed_component.html
{% for room in rooms%}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="{% url 'user-profile' room.host.id%}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{room.host.avatar_url}}" />
            </div>
            <span>@{{room.host.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{room.created|timesince}} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{%url 'room' room.id%}">{{room.name}}</a>
        <p>
            {{ room.description|truncatechars:70 }}
        </p>
    </div>
    <div class="roomListRoom__meta">
        <a href="{%url 'room' room.id%}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{room.participants.count}}
        </a>
        <p class="roomListRoom__topic">{{room.topic}}</p>
    </div>
</div>
{%endfor%}

base/templates/base/home.html
{% extends 'main.html' %}

{% block content %}
<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {%include 'base/topic_component.html'%}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form class="header__search" method="get" action="">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input placeholder="Search for posts" name="q" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
        </div>
      </div>
      <div class="roomList__header">
        <div>
          <h2>Study Room</h2>
          <p>{{room_cnt}} Rooms available</p>
        </div>
        <a class="btn btn--main" href="{%url 'create-room'%}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z">
            </path>
          </svg>
          Create Room
        </a>
      </div>  
      {%include 'base/feed_component.html'%}
    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'base/activity_component.html' with messages=room_messages %}
    <!-- Activities End -->
  </div>
</main>

{% endblock content %}

base/templates/base/login.html
{% extends 'main.html' %}

{% block content %}
    <main class="auth layout">
      <div class="container">
        <div class="layout__box">
          <div class="layout__boxHeader">
            <div class="layout__boxTitle">
              <h3>Login</h3>
            </div>
          </div>
          <div class="layout__body">
            <h2 class="auth__tagline">Find your study partner</h2>


            <form class="form" action="{% url 'login' %}" method="POST">
              {% csrf_token %}
              <div class="form__group">
                <label for="user_name">Email</label>
                <input id="user_name" name="email" type="email" placeholder="e.g. dennis_ivy"/>
              </div>
              <div class="form__group">
                <label for="password">Password</label>
                <input id="password" name="password" type="password" placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"/>
              </div>

              <button class="btn btn--main" type="submit">
                <svg
                  version="1.1"
                  xmlns="http://www.w3.org/2000/svg"
                  width="32"
                  height="32"
                  viewBox="0 0 32 32">
                  <title>lock</title>
                  <path
                    d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                  ></path>
                  <path
                    d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                  ></path></svg>
                Login
              </button>
            </form>

            <div class="auth__action">
              <p>Haven't signed up yet?</p>
              <a href="{% url 'register' %}" class="btn btn--link">Sign Up</a>
            </div>

          </div>
        </div>
      </div>
    </main>
    
{% endblock content %}
    
    
    
    
    
    

base/templates/base/notallowed.html
<div>
    <body bgcolor=red>
        <div>
            <center>
    <br><br><br> <table bgcolor="grey" cellpadding="20">
        <tr>
            <td>
                <h1>You are not allowed here.</h1>
            </td>
        </tr>
    </table>
</center>
        </div>
    </body>
</div>

base/templates/base/profile.html
{% extends 'main.html' %}

{% block content %}


<main class="profile-page layout layout--3">
    <div class="container">
        <!-- Topics Start -->
        {% include 'base/topic_component.html' %}
        <!-- Topics End -->

        <!-- Room List Start -->
        <div class="roomList">
            <div class="profile">
                <div class="profile__avatar">
                    <div class="avatar avatar--large active">
                        <img src="{{user.avatar_url}}" />
                    </div>
                </div>
                <div class="profile__info">
                    <h3>{{user.name}}</h3>
                    <p>@{{user.username}}</p>
                    {% if request.user == user %}
                    <a href="{% url 'update-user' user.id %}" class="btn btn--main btn--pill">Edit Profile</a>
                    {%endif%}
                </div>
                <div class="profile__about">
                    <h3>About</h3>
                    <p>
                        {{user.bio}}
                    </p>
                </div>
            </div>

            <div class="roomList__header">
                <div>
                    <h2>Study Rooms Hosted by {{user.name}}</a>
                    </h2>
                </div>
            </div>
            {%include 'base/feed_component.html' with rooms=rooms%}
        </div>
        <!-- Room List End -->

        <!-- Activities Start -->
        {% include 'base/activity_component.html' with messages=user_messages %}
        <!-- Activities End -->
    </div>
</main>

{% endblock content %}

base/templates/base/topic_component.html
<div class="topics">
    <div class="topics__header">
        <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
        <li>
            <a href="{%url 'home'%}" class="active">All Topics<span>{{topics.count}}</span></a>
        </li>
        {% for topic in topics %}
        <li>
            <a href="{% url 'home' %}?q={{topic.name}}">{{topic.name}} <span>{{topic.room_set.count}}</span></a>
        </li>
        {%endfor%}
    </ul>
    <a class="btn btn--link" href="{% url 'topics' %}">
        More
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
            <title>arrow-right-slim</title>
            <path d="M11.293 4.707L17.586 11H4v2h13.586l-6.293 6.293 1.414 1.414L21.414 12l-8.707-8.707-1.414 1.414z">
            </path>
        </svg>
        </svg>
    </a>
</div>

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}

<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title> 
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form class="header__search" method="get" action="">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input placeholder="Search for topics" name="q"/>
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{%url 'home'%}" class="active">All Topics <span> {{topics.count}}</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="{%url 'home'%}?q={{topic.name}}"> {{topic.name}} <span> {{topic.room_set.count}}</span></a>
          </li>
          {%endfor%}
        </ul>
      </div>
    </div>
  </div>
</main>

<script src="script.js"></script>

{% endblock content %}

base/templates/base/update-user.html
{%extends 'main.html' %}

{% block content %}

<main class="update-account layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Edit your profile</h3>
        </div>
      </div>
      <div class="layout__body">
        <form class="form" action="" method="post" enctype="multipart/form-data">
          {% csrf_token %}
          {% for field in form %}
          <div class="form__group">
            <label for="profile_pic">{{field.label}}</label>
            {{field}}
          </div>
          {%endfor%}
          <div class="form__action">
            <a class="btn btn--dark" href="index.html">Cancel</a>
            <button class="btn btn--main" type="submit">Update</button>
          </div>
        </form>
      </div>
    </div>
  </div>
  </div>
</main>
{% endblock content %}